# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: performance_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ipss_pb2 as ipss__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='performance_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16performance_data.proto\x1a\nipss.proto\"$\n\x04\x44\x61ta\x12\r\n\x05score\x18\x01 \x01(\x02\x12\r\n\x05index\x18\x02 \x01(\x05\"\xa7\x01\n\x06Solver\x12!\n\ndefinition\x18\x01 \x01(\x0b\x32\r.ipss.Service\x12>\n\x14\x65nviroment_variables\x18\x02 \x03(\x0b\x32 .Solver.EnviromentVariablesEntry\x1a:\n\x18\x45nviromentVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8e\x01\n\x0bPerformance\x12\x17\n\x06solver\x18\x01 \x01(\x0b\x32\x07.Solver\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.Performance.DataEntry\x12\x0c\n\x04hash\x18\x03 \x01(\t\x1a\x32\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Data:\x02\x38\x01\"0\n\x12SolversPerformance\x12\x1a\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0c.Performanceb\x06proto3'
  ,
  dependencies=[ipss__pb2.DESCRIPTOR,])




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='Data.score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='Data.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=74,
)


_SOLVER_ENVIROMENTVARIABLESENTRY = _descriptor.Descriptor(
  name='EnviromentVariablesEntry',
  full_name='Solver.EnviromentVariablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Solver.EnviromentVariablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Solver.EnviromentVariablesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=244,
)

_SOLVER = _descriptor.Descriptor(
  name='Solver',
  full_name='Solver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='definition', full_name='Solver.definition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enviroment_variables', full_name='Solver.enviroment_variables', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SOLVER_ENVIROMENTVARIABLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=244,
)


_PERFORMANCE_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='Performance.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Performance.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Performance.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=389,
)

_PERFORMANCE = _descriptor.Descriptor(
  name='Performance',
  full_name='Performance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='solver', full_name='Performance.solver', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Performance.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='Performance.hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PERFORMANCE_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=389,
)


_SOLVERSPERFORMANCE = _descriptor.Descriptor(
  name='SolversPerformance',
  full_name='SolversPerformance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SolversPerformance.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=439,
)

_SOLVER_ENVIROMENTVARIABLESENTRY.containing_type = _SOLVER
_SOLVER.fields_by_name['definition'].message_type = ipss__pb2._SERVICE
_SOLVER.fields_by_name['enviroment_variables'].message_type = _SOLVER_ENVIROMENTVARIABLESENTRY
_PERFORMANCE_DATAENTRY.fields_by_name['value'].message_type = _DATA
_PERFORMANCE_DATAENTRY.containing_type = _PERFORMANCE
_PERFORMANCE.fields_by_name['solver'].message_type = _SOLVER
_PERFORMANCE.fields_by_name['data'].message_type = _PERFORMANCE_DATAENTRY
_SOLVERSPERFORMANCE.fields_by_name['data'].message_type = _PERFORMANCE
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Solver'] = _SOLVER
DESCRIPTOR.message_types_by_name['Performance'] = _PERFORMANCE
DESCRIPTOR.message_types_by_name['SolversPerformance'] = _SOLVERSPERFORMANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'performance_data_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)

Solver = _reflection.GeneratedProtocolMessageType('Solver', (_message.Message,), {

  'EnviromentVariablesEntry' : _reflection.GeneratedProtocolMessageType('EnviromentVariablesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SOLVER_ENVIROMENTVARIABLESENTRY,
    '__module__' : 'performance_data_pb2'
    # @@protoc_insertion_point(class_scope:Solver.EnviromentVariablesEntry)
    })
  ,
  'DESCRIPTOR' : _SOLVER,
  '__module__' : 'performance_data_pb2'
  # @@protoc_insertion_point(class_scope:Solver)
  })
_sym_db.RegisterMessage(Solver)
_sym_db.RegisterMessage(Solver.EnviromentVariablesEntry)

Performance = _reflection.GeneratedProtocolMessageType('Performance', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERFORMANCE_DATAENTRY,
    '__module__' : 'performance_data_pb2'
    # @@protoc_insertion_point(class_scope:Performance.DataEntry)
    })
  ,
  'DESCRIPTOR' : _PERFORMANCE,
  '__module__' : 'performance_data_pb2'
  # @@protoc_insertion_point(class_scope:Performance)
  })
_sym_db.RegisterMessage(Performance)
_sym_db.RegisterMessage(Performance.DataEntry)

SolversPerformance = _reflection.GeneratedProtocolMessageType('SolversPerformance', (_message.Message,), {
  'DESCRIPTOR' : _SOLVERSPERFORMANCE,
  '__module__' : 'performance_data_pb2'
  # @@protoc_insertion_point(class_scope:SolversPerformance)
  })
_sym_db.RegisterMessage(SolversPerformance)


_SOLVER_ENVIROMENTVARIABLESENTRY._options = None
_PERFORMANCE_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
