FROM python:3.11
RUN pip3 install git+https://github.com/pee-rpc-protocol/pee-rpc \
    git+https://github.com/celaut-project/node-driver \
    git+https://github.com/celaut-project/resource-manager \
    onnxruntime==1.16.0 iterators==0.2.0
