# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/instances.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/instances.proto',
  package='protobufs.instances',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19protobufs/instances.proto\x12\x13protobufs.instances\"\x19\n\x06\x43lause\x12\x0f\n\x07literal\x18\x01 \x03(\x05\"2\n\x03\x43nf\x12+\n\x06\x63lause\x18\x01 \x03(\x0b\x32\x1b.protobufs.instances.Clause\"\"\n\x0eInterpretation\x12\x10\n\x08variable\x18\x01 \x03(\x05\"\x12\n\x10WhoAreYourParams2X\n\x06Random\x12N\n\tRandomCnf\x12%.protobufs.instances.WhoAreYourParams\x1a\x18.protobufs.instances.Cnf\"\x00\x32R\n\x06Solver\x12H\n\x05Solve\x12\x18.protobufs.instances.Cnf\x1a#.protobufs.instances.Interpretation\"\x00\x62\x06proto3'
)




_CLAUSE = _descriptor.Descriptor(
  name='Clause',
  full_name='protobufs.instances.Clause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='literal', full_name='protobufs.instances.Clause.literal', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=75,
)


_CNF = _descriptor.Descriptor(
  name='Cnf',
  full_name='protobufs.instances.Cnf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clause', full_name='protobufs.instances.Cnf.clause', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=127,
)


_INTERPRETATION = _descriptor.Descriptor(
  name='Interpretation',
  full_name='protobufs.instances.Interpretation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variable', full_name='protobufs.instances.Interpretation.variable', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=163,
)


_WHOAREYOURPARAMS = _descriptor.Descriptor(
  name='WhoAreYourParams',
  full_name='protobufs.instances.WhoAreYourParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=183,
)

_CNF.fields_by_name['clause'].message_type = _CLAUSE
DESCRIPTOR.message_types_by_name['Clause'] = _CLAUSE
DESCRIPTOR.message_types_by_name['Cnf'] = _CNF
DESCRIPTOR.message_types_by_name['Interpretation'] = _INTERPRETATION
DESCRIPTOR.message_types_by_name['WhoAreYourParams'] = _WHOAREYOURPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Clause = _reflection.GeneratedProtocolMessageType('Clause', (_message.Message,), {
  'DESCRIPTOR' : _CLAUSE,
  '__module__' : 'protobufs.instances_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.instances.Clause)
  })
_sym_db.RegisterMessage(Clause)

Cnf = _reflection.GeneratedProtocolMessageType('Cnf', (_message.Message,), {
  'DESCRIPTOR' : _CNF,
  '__module__' : 'protobufs.instances_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.instances.Cnf)
  })
_sym_db.RegisterMessage(Cnf)

Interpretation = _reflection.GeneratedProtocolMessageType('Interpretation', (_message.Message,), {
  'DESCRIPTOR' : _INTERPRETATION,
  '__module__' : 'protobufs.instances_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.instances.Interpretation)
  })
_sym_db.RegisterMessage(Interpretation)

WhoAreYourParams = _reflection.GeneratedProtocolMessageType('WhoAreYourParams', (_message.Message,), {
  'DESCRIPTOR' : _WHOAREYOURPARAMS,
  '__module__' : 'protobufs.instances_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.instances.WhoAreYourParams)
  })
_sym_db.RegisterMessage(WhoAreYourParams)



_RANDOM = _descriptor.ServiceDescriptor(
  name='Random',
  full_name='protobufs.instances.Random',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=185,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='RandomCnf',
    full_name='protobufs.instances.Random.RandomCnf',
    index=0,
    containing_service=None,
    input_type=_WHOAREYOURPARAMS,
    output_type=_CNF,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANDOM)

DESCRIPTOR.services_by_name['Random'] = _RANDOM


_SOLVER = _descriptor.ServiceDescriptor(
  name='Solver',
  full_name='protobufs.instances.Solver',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=275,
  serialized_end=357,
  methods=[
  _descriptor.MethodDescriptor(
    name='Solve',
    full_name='protobufs.instances.Solver.Solve',
    index=0,
    containing_service=None,
    input_type=_CNF,
    output_type=_INTERPRETATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOLVER)

DESCRIPTOR.services_by_name['Solver'] = _SOLVER

# @@protoc_insertion_point(module_scope)
